library(datapasta)
df_paste()

dt <- data.frame(
  stringsAsFactors = FALSE,
                V1 = c(1L,2L,3L,4L,5L,6L,7L,8L,
                       9L,10L,11L,12L,13L,14L,15L,16L,17L,18L,19L,
                       20L,21L,22L,23L,24L,25L,26L,27L,28L,29L,30L,31L,
                       32L,33L,34L,35L,36L,37L,38L,39L,40L,41L,42L,
                       43L,44L,45L,46L,47L,48L,49L,50L,51L,52L,53L,54L,
                       55L,56L,57L,58L,59L,60L,61L,62L,63L,64L,65L,
                       66L,67L,68L,69L,70L,71L,72L,73L,74L,75L,76L,
                       77L,78L,79L,80L,81L,82L,83L,84L,85L,86L,87L,88L,
                       89L,90L,91L,92L,93L,94L,95L,96L),
                V2 = c(0L,0L,0L,0L,0L,0L,0L,0L,
                       0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,
                       0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,
                       0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,
                       0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,
                       0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,
                       0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,0L,
                       0L,0L,0L),
                V3 = c("Adel, Tasmin",
                       "Afuape, Ekundayo","Arthur, Andrew","Athaide, Megan","Baragar, Signy",
                       "Baraka, Eugene","Barrera Patlán, Andrés",
                       "Blackman, Asia","Bouchard, Megane","Boudi, Ibtissam",
                       "Brodovsky, Leah","Busa, Giovanna","Butler, Megan",
                       "Caminsky, Natasha","Carroll, Siobhan","Caviedes, David",
                       "Chiv, Maximilian","Churipuy, Maureen","Combet, Virginie",
                       "Côté Corriveau, Gabriel","Dalal, Sanya","Dinu, Tudor",
                       "Elkaïm, Lior","Engler, Julie","Eruala, Levi",
                       "Faraji, Sana-Eve","Fazio, Marissa","Fleming, Daniela",
                       "Gebreweldi, Frezghi","Gibson, Diana","González, Nadia",
                       "Gruber, Paula","Haig, Laurie","Holmes, Kieran","Houle, Jonathan",
                       "Igweokpala, Samuel","James, Britnei","Jutras, Kevin",
                       "Juwono, Stephen","Khattak, Hashim",
                       "Koripalli, Maanasa","Lakrouf, Racha","Lall, Rina","Li, Jennifer",
                       "Li, Shirly","Logel, Maggie","Lu, Ingrid","Lu, Sally",
                       "Ma, Qihang","Modler, Jacqueline","Moidu, Nora",
                       "Moncado, Jack","Moreau, Juliane","Morgan, Liam",
                       "Morrison, Nora","Nichols, Vanessa","Noza, Aklil",
                       "Nwaogwugwu, Betty","Osagie, Rachael","Ouizzane, Soukaina",
                       "Pannunzio, Matteo","Parisa, Tahlil","Parsons, Kristina",
                       "Perlman-Arrow, Sara","Pirwani, Sabah","Poirier, Mathieu",
                       "Qiang, Vivian","Reveiz, Manuela","Robitaille, Stephan",
                       "Salimian, Samaneh","Sam, Yasmine","Sambou, Patrick",
                       "Saremi Naeeni, Saba","Schurr, Alex","Semelhago, Claire",
                       "Senga, Joyeuse","Shah, Malhar","Shankar, Sharat",
                       "Shephard, Rosemarie","Shiraz, Mehrunnisa","Sidhu, Harsimren",
                       "Simba, Suzanne","Spiegler, Gabriella",
                       "Streef, Katrina","Sule, Olaoluwa","Swain, Josh","Thibault, Melina",
                       "Tian, Jingyi","Tope, Parker","Vanden Eynde, Claire",
                       "Wan, Xinbei","Wang, Wanqi","Weight, Charlene",
                       "Zary, Miranda","Zhang, Hana","Zhang, Yang"),
                V4 = c(261023896L,261028920L,
                       260957835L,261011767L,261017146L,261021296L,260504360L,
                       260614529L,261025111L,261021283L,261021315L,261022735L,
                       260958242L,260430209L,261018064L,261021621L,260585109L,
                       261022079L,260405786L,261002424L,260776903L,
                       260782701L,260638820L,260992806L,261029330L,260770240L,
                       260999825L,261022719L,260959314L,261011806L,261011044L,
                       260411842L,261002642L,261019737L,260222305L,260965741L,
                       261020671L,260736087L,261007383L,261000646L,
                       260857020L,260583783L,260549552L,260783569L,261021638L,
                       260994390L,260773949L,260961227L,260761707L,261019994L,
                       260800290L,260743113L,261010790L,261025535L,261005863L,
                       261011123L,261024501L,261011132L,260995236L,
                       260689767L,260871339L,261021086L,260532467L,260807830L,
                       261026953L,260402574L,260799300L,260768396L,260586343L,
                       261026386L,261016497L,260964380L,260745869L,260952531L,
                       261015352L,261027904L,261020481L,261015306L,
                       261019987L,261018519L,260684812L,260947685L,260863076L,
                       261024609L,260958354L,261021774L,260866928L,260955758L,
                       260706334L,261023478L,260777034L,261023391L,260632461L,
                       260728712L,261023486L,261009389L),
                V5 = c("Web Registered",
                       "Web Registered","Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered","Web Registered",
                       "Web Registered","Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered","Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered","Web Registered",
                       "Web Registered","Web Registered"),
                V6 = c("Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs *","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs *",
                       "Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs *",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs *","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs",
                       "Masters & Grad Dips & Certs","Masters & Grad Dips & Certs"),
                V7 = c(4,4,4,4,4,4,4,4,4,4,4,
                       4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,
                       4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,
                       4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,
                       4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,
                       4,4,4,4,4,4,4,4,4),
                V8 = c("Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Medical Resident *","Master of Science",
                       "Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Medical Resident *",
                       "Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Medical Resident *","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Medical Resident *",
                       "Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science",
                       "Master of Science","Master of Science","Master of Science"),
                V9 = c("MSc in Public Health -N",
                       "MSc Epidemiology -N","MSc Epidemiology -T",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N","MSc Epidemiology -T",
                       "MSc Epidemiology -T","MSc in Public Health -N",
                       "MSc Epidemiology -T","MSc Epidemiology -T",
                       "MSc in Public Health -N","Medical Resident *","MSc Epidemiology -T",
                       "MSc in Public Health -N","MSc Epidemiology -T",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc Epidemiology -T","MSc in Public Health -N",
                       "MSc in Public Health -N","Medical Resident *","MSc Epidemiology -T",
                       "MSc Epidemiology -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc Epidemiology -T","MSc in Public Health -N","Medical Resident *",
                       "MSc Epidemiology -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc Epidemiology -T",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc Epidemiology -N","MSc Epidemiology -T",
                       "MSc Epidemiology -T","MSc Epidemiology -T",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc Epidemiology -T",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc Dental Sciences -T",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc Epidemiology -T","MSc Epidemiology -T","MSc in Public Health -N",
                       "MSc Epidemiology -T","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "Medical Resident *","MSc Epidemiology -T",
                       "MSc in Public Health -N","MSc Epidemiology -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc Epidemiology -T",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc Epidemiology -T","MSc Epidemiology -T","MSc in Public Health -N",
                       "MSc Epidemiology -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N","MSc Epidemiology -T","MSc Epidemiology -T",
                       "MSc in Public Health -N","MSc in Public Health -N",
                       "MSc in Public Health -N"),
               V10 = c("Public Health -N",
                       "Epidemiology -N","Epidemiology -T","Public Health -N",
                       "Public Health -N","Public Health -N","Public Health -N",
                       "Epidemiology -T","Epidemiology -T","Public Health -N",
                       "Epidemiology -T","Epidemiology -T","Public Health -N",
                       "General Surgery *","Epidemiology -T","Public Health -N",
                       "Epidemiology -T","Public Health -N","Public Health -N",
                       "Epidemiology -T","Public Health -N","Public Health -N",
                       "Neurosurgery *","Epidemiology -T","Epidemiology -N",
                       "Public Health -N","Public Health -N",
                       "Public Health -N","Public Health -N","Public Health -N",
                       "Public Health -N","Public Health -N","Epidemiology -T",
                       "Public Health -N","Internal Medicine-Subspecialty *",
                       "Epidemiology -N","Public Health -N","Public Health -N",
                       "Epidemiology -T","Public Health -N","Public Health -N",
                       "Public Health -N","Public Health -N","Public Health -N",
                       "Epidemiology -N","Epidemiology -T","Epidemiology -T",
                       "Epidemiology -T","Public Health -N","Public Health -N",
                       "Public Health -N","Public Health -N","Public Health -N",
                       "Public Health -N","Epidemiology -T","Public Health -N",
                       "Public Health -N","Public Health -N",
                       "Dental Sciences -T","Public Health -N","Public Health -N",
                       "Epidemiology -T","Epidemiology -T","Public Health -N",
                       "Epidemiology -T","Public Health -N","Public Health -N",
                       "Public Health -N","General Surgery *","Epidemiology -T",
                       "Public Health -N","Epidemiology -N","Public Health -N",
                       "Public Health -N","Public Health -N","Public Health -N",
                       "Epidemiology -T","Public Health -N",
                       "Public Health -N","Public Health -N","Public Health -N",
                       "Epidemiology -T","Epidemiology -T","Public Health -N",
                       "Epidemiology -N","Public Health -N","Public Health -N",
                       "Public Health -N","Public Health -N","Public Health -N",
                       "Public Health -N","Epidemiology -T","Epidemiology -T",
                       "Public Health -N","Public Health -N","Public Health -N"),
               V11 = c("Per Credit","Per Credit",
                       "Thesis Full-time","Per Credit","Per Credit","Per Credit",
                       "Per Credit","Thesis Full-time","Thesis Full-time",
                       "Per Credit","Thesis Full-time","Thesis Full-time",
                       "Per Credit","N/A","Thesis Full-time","Per Credit",
                       "Thesis Full-time","Per Credit","Per Credit",
                       "Thesis Full-time","Per Credit","Per Credit","N/A",
                       "Thesis Full-time","Per Credit","Per Credit","Per Credit","Per Credit",
                       "Per Credit","Per Credit","Per Credit","Per Credit",
                       "Thesis Full-time","Per Credit","N/A","Per Credit",
                       "Per Credit","Per Credit","Thesis Full-time",
                       "Per Credit","Per Credit","Per Credit","Per Credit",
                       "Per Credit","Per Credit","Thesis Full-time","Thesis Full-time",
                       "Thesis Full-time","Per Credit","Per Credit",
                       "Per Credit","Per Credit","Per Credit","Per Credit",
                       "Thesis Full-time","Per Credit","Per Credit","Per Credit",
                       "Thesis Full-time","Per Credit","Per Credit",
                       "Thesis Full-time","Thesis Full-time","Per Credit",
                       "Thesis Full-time","Per Credit","Per Credit","Per Credit","N/A",
                       "Thesis Full-time","Per Credit","Per Credit","Per Credit",
                       "Per Credit","Per Credit","Per Credit",
                       "Thesis Full-time","Per Credit","Per Credit","Per Credit",
                       "Per Credit","Thesis Full-time","Thesis Full-time","Per Credit",
                       "Per Credit","Per Credit","Per Credit","Per Credit",
                       "Per Credit","Per Credit","Per Credit",
                       "Thesis Full-time","Thesis Full-time","Per Credit","Per Credit",
                       "Per Credit"),
               V12 = c("N/A","Intl:2348120682901",
                       "(613) 290-4062","(647) 569-0224","N/A","N/A",
                       "(306) 514-1483","Intl:12464164065","(514) 972-8442",
                       "(613) 668-3683","(519 ) 823-9394","(613) 322-2001","N/A",
                       "(519) 630-0636","N/A","Intl:0115712691547",
                       "(514) 337-2138","N/A","(514) 824-9801","N/A","(438) 921-0618",
                       "(519) 753-4156","(514) 839-2895","N/A",
                       "Intl:2347066939482","(613) 265-0834","(647) 808-1951","N/A",
                       "(00) Intl:00249969215721","(867) 445-5373","N/A",
                       "(647) 548-5551","(613) 733-4509","N/A","(514) 737-6629",
                       "Intl:08061258754","N/A","(514) 601-9985","(604) 929-2890",
                       "(780) 433-1329","(309) 660-7067","(514) 214-7510",
                       "(514) 466-2577","(226) 998-4526","N/A","N/A",
                       "(514) 484-6678","N/A","Intl:008613917131013","(613) 218-6933",
                       "(343) 999-4158","(514) 486-7743","(514) 564-6853",
                       "(289) 684-9717","(519) 504-4990","(1)","N/A",
                       "(438) 520-8573","(438) 223-2397","(514) 207-1668","(514) 484-2181",
                       "Ext:88 Intl:01867309432","(514) 927-7316",
                       "(514) 621-9288","(613) 712-1514","(613) 219-8665",
                       "(604) 241-5885","(301) 983-0275","(514) 218-7050","(438) 993-2278",
                       "(416) 530-9784","(+220) 385-3942 Intl:4460660",
                       "(514) 497-0289","N/A","N/A","Intl:0787322960","N/A",
                       "Intl:919503663790","(416) 923-9034","(647) 222-1292",
                       "(778) 882-9911","(613) 898-6287","(514) 836-5286",
                       "(905) 939-0514","Intl:2348092533953","(204) 227-9449",
                       "(514) 713-0930","Intl:85262318783","(438) 927-8097","N/A",
                       "(514) 549-9599","(86)","(514) 234-0348",
                       "(416) 951-0780","N/A","(1)"),
               V13 = c("tasmin.adel@mail.mcgill.ca",
                       "ekundayo.afuape@mail.mcgill.ca",
                       "andrew.arthur@mail.mcgill.ca","megan.athaide@mail.mcgill.ca",
                       "signy.baragar@mail.mcgill.ca","eugene.baraka@mail.mcgill.ca",
                       "andres.barrerapatlan@mail.mcgill.ca",
                       "asia.blackman@mail.mcgill.ca","megane.bouchard@mail.mcgill.ca",
                       "ibtissam.boudi@mail.mcgill.ca","leah.brodovsky@mail.mcgill.ca",
                       "giovanna.busa@mail.mcgill.ca","megan.butler@mail.mcgill.ca",
                       "natasha.caminsky@mail.mcgill.ca",
                       "siobhan.carroll@mail.mcgill.ca","david.caviedes@mail.mcgill.ca",
                       "maximilian.chiv@mail.mcgill.ca","maureen.churipuy@mail.mcgill.ca",
                       "virginie.combet@mail.mcgill.ca",
                       "gabriel.cotecorriveau@mail.mcgill.ca","sanya.dalal@mail.mcgill.ca",
                       "tudor.dinu@mail.mcgill.ca","lior.elkaim@mail.mcgill.ca",
                       "julie.engler@mail.mcgill.ca","levi.eruala@mail.mcgill.ca",
                       "sana-eve.faraji@mail.mcgill.ca","marissa.fazio@mail.mcgill.ca",
                       "daniela.fleming@mail.mcgill.ca",
                       "frezghi.gebreweldi@mail.mcgill.ca","diana.gibson@mail.mcgill.ca",
                       "nadia.gonzalez@mail.mcgill.ca","paula.gruber@mail.mcgill.ca",
                       "laurie.haig@mail.mcgill.ca","kieran.holmes@mail.mcgill.ca",
                       "jonathan.houle@mail.mcgill.ca",
                       "samuel.igweokpala@mail.mcgill.ca","britnei.james@mail.mcgill.ca",
                       "kevin.jutras@mail.mcgill.ca","stephen.juwono@mail.mcgill.ca",
                       "hashim.khattak@mail.mcgill.ca",
                       "maanasa.koripalli@mail.mcgill.ca","racha.lakrouf@mail.mcgill.ca",
                       "rina.lall@mail.mcgill.ca","wanjin.li@mail.mcgill.ca",
                       "jiaying.li2@mail.mcgill.ca","margaret.logel@mail.mcgill.ca",
                       "ingrid.lu@mail.mcgill.ca","sally.lu@mail.mcgill.ca",
                       "qihang.ma@mail.mcgill.ca","jacqueline.modler@mail.mcgill.ca",
                       "nora.moidu@mail.mcgill.ca","jack.moncado@mail.mcgill.ca",
                       "juliane.moreau@mail.mcgill.ca","liam.morgan@mail.mcgill.ca",
                       "nora.morrison@mail.mcgill.ca",
                       "vanessa.nichols@mail.mcgill.ca","aklil.noza@mail.mcgill.ca",
                       "betty.nwaogwugwu@mail.mcgill.ca","rachael.osagie@mail.mcgill.ca",
                       "soukaina.ouizzane@mail.mcgill.ca",
                       "matteo.pannunzio@mail.mcgill.ca","tahlil.parisa@mail.mcgill.ca",
                       "kristina.parsons@mail.mcgill.ca","sara.perlman-arrow@mail.mcgill.ca",
                       "sabah.pirwani@mail.mcgill.ca",
                       "mathieu.poirier3@mail.mcgill.ca","vivian.qiang@mail.mcgill.ca",
                       "manuela.reveiz@mail.mcgill.ca","stephan.robitaille2@mail.mcgill.ca",
                       "samaneh.salimian@mail.mcgill.ca",
                       "yasmine.sam@mail.mcgill.ca","patrick.sambou@mail.mcgill.ca",
                       "saba.saremi@mail.mcgill.ca","alexander.schurr@mail.mcgill.ca",
                       "claire.semelhago@mail.mcgill.ca","joyeuse.senga@mail.mcgill.ca",
                       "malhar.shah@mail.mcgill.ca",
                       "sharat.shankar@mail.mcgill.ca","rosemarie.shephard@mail.mcgill.ca",
                       "mehrunnisa.shiraz@mail.mcgill.ca","harsimren.sidhu@mail.mcgill.ca",
                       "suzanne.simba@mail.mcgill.ca",
                       "gabriella.spiegler@mail.mcgill.ca","katrina.streef@mail.mcgill.ca",
                       "olaoluwa.sule@mail.mcgill.ca","joshua.swain@mail.mcgill.ca",
                       "melina.thibault@mail.mcgill.ca","jingyi.tian@mail.mcgill.ca",
                       "parker.tope@mail.mcgill.ca",
                       "claire.vandeneynde@mail.mcgill.ca","xinbei.wan@mail.mcgill.ca",
                       "wanqi.wang@mail.mcgill.ca","charlene.weight@mail.mcgill.ca",
                       "miranda.zary@mail.mcgill.ca","ruhan.zhang@mail.mcgill.ca",
                       "yang.zhang8@mail.mcgill.ca"),
               V14 = c(NA,NA,NA,NA,NA,NA,NA,NA,
                       NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,
                       NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,
                       NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,
                       NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,
                       NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,
                       NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,
                       NA,NA,NA)
)

library(tidyverse)
dt$V13 %>% dput()
